In [115]:
import numpy as np

np.set_printoptions(precision=4, suppress=True)
np.random.seed(0)

batch = 64
seq_len = 1024    
model_dim = 768
d_k = 64
X = np.random.randn(batch, seq_len, model_dim) 
print("X shape:", X.shape, "\nX:\n", X, "\n")

X shape: (64, 1024, 768) 
X:
 [[[ 1.7641  0.4002  0.9787 ... -1.1029 -0.1017  0.0193]
  [ 1.8496 -0.2142 -0.499  ...  0.2838 -0.2822 -1.1582]
  [-1.6194 -0.511   1.7406 ... -0.4966  1.3364 -0.12  ]
  ...
  [ 0.1489 -0.0358  0.5394 ... -0.4339 -0.0241 -0.7906]
  [-0.7217  1.5015 -0.312  ... -0.3482 -0.6375 -0.1208]
  [-1.6499  0.5804 -0.5619 ... -1.313   0.4138 -0.0727]]

 [[-0.1905 -2.6558 -1.1977 ...  0.6264  0.075  -0.3494]
  [ 0.1491 -1.798  -1.2155 ...  2.0108 -0.7833  0.7058]
  [ 2.1964  1.381   0.0787 ...  1.1391 -0.3538 -0.0072]
  ...
  [ 0.8212  0.2416 -0.0699 ...  0.8717  0.792   2.3142]
  [ 0.3726  0.2452 -0.7938 ...  1.2685  0.8727 -0.6245]
  [-0.6843 -1.5222  0.5123 ...  0.9219  1.4332  1.8321]]

 [[-0.3146  0.5689 -0.1206 ... -1.0242 -0.6635  1.3492]
  [-0.2775  0.3374  0.3891 ...  1.1123 -0.299   2.2719]
  [ 1.2357 -0.3459 -0.9964 ...  0.2468 -0.7418  1.0765]
  ...
  [-0.5187 -1.6532  0.593  ...  0.5489  0.2557  1.3028]
  [ 2.5934 -1.2943 -0.9694 ... -0.9416 -1.2423 -0.83

In [116]:
Wq = np.random.randn(model_dim, d_k) *  (1 / np.sqrt(model_dim))
Wk = np.random.randn(model_dim, d_k)  * (1 / np.sqrt(model_dim))
Wv = np.random.randn(model_dim, d_k)  * (1 / np.sqrt(model_dim))

print("Wq:\n", Wq, "\n")
print("Wk:\n", Wk, "\n")
print("Wv:\n", Wv, "\n")

Wq:
 [[ 0.0608  0.0556 -0.0212 ...  0.0077 -0.0292 -0.0234]
 [-0.0544  0.008  -0.0174 ... -0.0442 -0.0239  0.0712]
 [-0.0076  0.0734 -0.0188 ...  0.0176  0.0148  0.0277]
 ...
 [ 0.0033  0.0283 -0.0263 ...  0.0055 -0.0499  0.0602]
 [ 0.0272 -0.0264  0.0719 ... -0.0034  0.0344 -0.0153]
 [ 0.0639  0.0466  0.0254 ... -0.069  -0.0146  0.006 ]] 

Wk:
 [[ 0.0129 -0.0068  0.0092 ...  0.0671  0.0014 -0.043 ]
 [ 0.0648  0.0598 -0.0224 ...  0.0073  0.0249  0.0114]
 [-0.0089  0.046   0.0458 ... -0.0506  0.0166 -0.0435]
 ...
 [-0.0138  0.0331  0.0278 ... -0.058  -0.033  -0.0232]
 [-0.0529  0.0181 -0.0099 ... -0.0109 -0.0527 -0.0299]
 [ 0.0339  0.0072 -0.0075 ... -0.0057  0.0559 -0.0232]] 

Wv:
 [[ 0.0464 -0.0369 -0.0389 ... -0.0623  0.0278 -0.0073]
 [ 0.0554  0.0731 -0.0091 ...  0.0449 -0.0211  0.0167]
 [ 0.0488  0.0552  0.0152 ...  0.0142 -0.0176  0.0215]
 ...
 [ 0.0042 -0.0221  0.0031 ... -0.0967 -0.0366  0.0276]
 [ 0.0169 -0.0366 -0.057  ... -0.0315  0.0308  0.0264]
 [-0.0161 -0.0418 -0.0165 ...

In [117]:
Q = X @ Wq  
K = X @ Wk
V = X @ Wv

print("Q:\n", Q, "\n")
print("K:\n", K, "\n")
print("V:\n", V, "\n")

Q:
 [[[-0.371   1.5416  0.0796 ...  0.2815  0.112   1.1259]
  [-0.9121  0.9408 -1.5043 ... -0.6713 -2.3714  0.4941]
  [ 1.3196  1.7835  0.2849 ...  0.6919 -0.2994  0.0918]
  ...
  [ 1.0853  0.461  -1.8612 ...  0.9356 -1.5536 -2.7244]
  [-2.4827  0.1853 -0.2677 ... -1.0266  0.83   -1.1398]
  [-0.2162 -0.7371  0.8582 ... -0.5644 -0.5572  0.0658]]

 [[-0.7421 -1.0949 -0.6959 ... -0.733   0.0608 -2.0647]
  [ 0.0325  0.5857 -1.3749 ...  0.6171  1.3417  0.2224]
  [-0.4382 -0.6185 -0.1138 ... -1.4115 -0.3417 -0.2298]
  ...
  [ 0.4    -0.9654 -0.3857 ... -1.576  -1.4248  0.452 ]
  [ 0.8752 -0.1439 -0.0864 ...  0.2565 -1.549   0.3942]
  [-0.1931 -0.4901  2.7529 ... -1.9023  0.4693 -0.7444]]

 [[-0.2778  0.3553 -0.3102 ... -0.7544  0.3499 -0.4072]
  [-1.2822 -0.4281  0.964  ...  1.764   0.1046  0.6802]
  [ 1.208   0.1301 -0.4847 ... -0.4463 -0.7139 -0.7198]
  ...
  [ 0.6699 -2.1312 -1.2264 ...  0.7184 -1.7502 -1.8324]
  [ 0.6989 -1.358   2.0592 ...  0.5876  0.3443 -0.066 ]
  [ 0.9302 -1.3496 -1.

In [118]:
scores = np.zeros((batch, seq_len, seq_len))
for b in range(batch):
    scores[b] = Q[b] @ K[b].T

print("Scores (QK^T):\n", scores, "\n")

Scores (QK^T):
 [[[ 10.5141   3.1401  -2.465  ...  -3.2264  14.9675  -0.9934]
  [ -3.9275  -5.2191  -4.2666 ...   9.3335 -12.8822  13.8804]
  [ -7.3056   8.1777 -13.5769 ...  -4.7237  -9.0737   0.0117]
  ...
  [ -0.337   -1.2804   8.0022 ...  -5.2571  -5.5952  25.4866]
  [  7.5894  -0.8469   8.0309 ...  10.6593   8.9641  -6.8066]
  [ -2.9115 -10.8244  -6.7216 ...  -2.7106 -13.5715   4.3251]]

 [[ -5.6714   7.6183   2.2334 ...   6.0281   9.0784  -8.4022]
  [ 15.3083   4.5683   1.759  ...  -1.2339  10.5652   9.8738]
  [ -4.5023   4.0731 -15.1212 ...   8.0679  10.2067 -21.4499]
  ...
  [ 15.0952   3.5465  -2.374  ...  11.9265   4.8648  -5.0449]
  [  5.9147  -2.5561  15.5674 ...   6.812   12.7361  -7.5605]
  [  3.3453   7.5558  -9.4095 ...  -2.7553   0.2162  -0.49  ]]

 [[ -7.1329 -10.1092   9.6945 ...   9.6494 -14.5718  12.6437]
  [  4.4911   1.7281   6.5222 ...   2.8696   9.4366 -14.1924]
  [-10.1667  -8.7163  -7.7113 ...  -0.8208   2.0362   5.9489]
  ...
  [  1.6007 -12.7464  -8.3125 ..

In [119]:
scaled_scores = scores / np.sqrt(d_k)
print("Scaled scores:\n", scaled_scores, "\n")

Scaled scores:
 [[[ 1.3143  0.3925 -0.3081 ... -0.4033  1.8709 -0.1242]
  [-0.4909 -0.6524 -0.5333 ...  1.1667 -1.6103  1.7351]
  [-0.9132  1.0222 -1.6971 ... -0.5905 -1.1342  0.0015]
  ...
  [-0.0421 -0.16    1.0003 ... -0.6571 -0.6994  3.1858]
  [ 0.9487 -0.1059  1.0039 ...  1.3324  1.1205 -0.8508]
  [-0.3639 -1.353  -0.8402 ... -0.3388 -1.6964  0.5406]]

 [[-0.7089  0.9523  0.2792 ...  0.7535  1.1348 -1.0503]
  [ 1.9135  0.571   0.2199 ... -0.1542  1.3206  1.2342]
  [-0.5628  0.5091 -1.8901 ...  1.0085  1.2758 -2.6812]
  ...
  [ 1.8869  0.4433 -0.2968 ...  1.4908  0.6081 -0.6306]
  [ 0.7393 -0.3195  1.9459 ...  0.8515  1.592  -0.9451]
  [ 0.4182  0.9445 -1.1762 ... -0.3444  0.027  -0.0613]]

 [[-0.8916 -1.2637  1.2118 ...  1.2062 -1.8215  1.5805]
  [ 0.5614  0.216   0.8153 ...  0.3587  1.1796 -1.7741]
  [-1.2708 -1.0895 -0.9639 ... -0.1026  0.2545  0.7436]
  ...
  [ 0.2001 -1.5933 -1.0391 ...  2.824   1.4835 -0.1386]
  [ 0.6531 -0.7924  0.1977 ... -0.585   1.1137  1.7173]
  [-0.141 

In [120]:
def stable_softmax(x):
    x = x - np.max(x, axis=-1, keepdims=True)
    exp = np.exp(x)
    return exp / np.sum(exp, axis=-1, keepdims=True)
print("Max scaled score:", np.max(scaled_scores))
print("Min scaled score:", np.min(scaled_scores))
attn_probs = stable_softmax(scaled_scores)
print("Attention weights:\n", attn_probs, "\n")

Max scaled score: 6.777088163208858
Min scaled score: -6.701069123401476
Attention weights:
 [[[0.0025 0.001  0.0005 ... 0.0005 0.0044 0.0006]
  [0.0004 0.0003 0.0004 ... 0.0019 0.0001 0.0034]
  [0.0002 0.0017 0.0001 ... 0.0003 0.0002 0.0006]
  ...
  [0.0004 0.0004 0.0012 ... 0.0002 0.0002 0.0109]
  [0.0017 0.0006 0.0018 ... 0.0025 0.002  0.0003]
  [0.0004 0.0002 0.0003 ... 0.0005 0.0001 0.0011]]

 [[0.0003 0.0017 0.0009 ... 0.0014 0.0021 0.0002]
  [0.0039 0.001  0.0007 ... 0.0005 0.0021 0.002 ]
  [0.0004 0.001  0.0001 ... 0.0017 0.0023 0.    ]
  ...
  [0.0041 0.001  0.0005 ... 0.0027 0.0011 0.0003]
  [0.0014 0.0005 0.0048 ... 0.0016 0.0033 0.0003]
  [0.0009 0.0015 0.0002 ... 0.0004 0.0006 0.0005]]

 [[0.0002 0.0002 0.002  ... 0.0019 0.0001 0.0028]
  [0.0011 0.0008 0.0014 ... 0.0009 0.002  0.0001]
  [0.0002 0.0002 0.0002 ... 0.0006 0.0008 0.0014]
  ...
  [0.0006 0.0001 0.0002 ... 0.0087 0.0023 0.0004]
  [0.0011 0.0003 0.0007 ... 0.0003 0.0018 0.0033]
  [0.0005 0.0005 0.0005 ... 0.0007 

In [121]:
print("Row sums:\n", np.sum(attn_probs, axis=-1), "\n")

Row sums:
 [[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]] 



In [122]:
print("Shapes check:")
print("X:", X.shape)           
print("Wq:", Wq.shape)          
print("Wk:", Wk.shape)           
print("Wv:", Wv.shape)            

print("Q:", Q.shape)           
print("K:", K.shape)           
print("V:", V.shape)            

print("scores:", scores.shape)    
print("attn_probs:", attn_probs.shape) 
print("output:", output.shape)  

Shapes check:
X: (64, 1024, 768)
Wq: (768, 64)
Wk: (768, 64)
Wv: (768, 64)
Q: (64, 1024, 64)
K: (64, 1024, 64)
V: (64, 1024, 64)
scores: (64, 1024, 1024)
attn_probs: (64, 1024, 1024)
output: (64, 1024, 64)


In [123]:
output = np.zeros((batch, seq_len, d_k))
for b in range(batch):
    output[b] = attn_probs[b] @ V[b]

print("Output Attention:\n", output, "\n")


Output Attention:
 [[[-0.1171 -0.0449 -0.0228 ... -0.0813 -0.0212  0.0288]
  [-0.007  -0.0969  0.0191 ...  0.0556  0.0265  0.0197]
  [ 0.0163 -0.0615 -0.037  ... -0.049  -0.0388  0.0479]
  ...
  [ 0.1053  0.0108  0.0561 ... -0.0592  0.1443 -0.0099]
  [-0.0584 -0.0778 -0.0684 ... -0.0287  0.0154 -0.1157]
  [-0.0809 -0.035   0.0514 ... -0.0013 -0.004   0.0441]]

 [[ 0.0342  0.0013  0.0114 ...  0.0406 -0.011   0.0216]
  [ 0.12   -0.0356 -0.0448 ...  0.1274 -0.1841  0.0185]
  [-0.0138 -0.0394 -0.0434 ...  0.0348 -0.0274  0.0448]
  ...
  [ 0.0299  0.0082 -0.0167 ...  0.0234 -0.0191  0.0536]
  [ 0.054  -0.0264  0.0868 ...  0.054  -0.0468  0.0332]
  [-0.0225  0.0129 -0.0874 ...  0.0197 -0.1291 -0.0488]]

 [[ 0.0706 -0.0012  0.0566 ...  0.0276  0.0113 -0.002 ]
  [ 0.0087  0.005  -0.0276 ...  0.0175  0.0222  0.0309]
  [ 0.1095  0.0868  0.028  ...  0.1111  0.0056 -0.1056]
  ...
  [ 0.0022  0.0873 -0.0368 ...  0.0217  0.0302 -0.085 ]
  [ 0.0278  0.0296  0.0444 ...  0.1008 -0.0489 -0.0686]
  [ 0.0